#!/usr/bin/env node
// Embeds tools/translation_mappings.json as C++ lookup tables for TranslationRegistry.
import { promises as fs } from 'node:fs';
import path from 'node:path';
import process from 'node:process';

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1')), '..');
const input = path.join(root, 'tools', 'translation_mappings.json');
const output = path.join(root, 'src', 'translation_mappings_data.cpp');

function emitMap(name, obj) {
    const lines = [`static const std::unordered_map<std::string, std::unordered_map<std::int32_t, std::int32_t>> ${name} = {`];
    for (const [pairKey, mapping] of Object.entries(obj)) {
        lines.push(`    {${JSON.stringify(pairKey)}, {`);
        for (const [fromId, toId] of Object.entries(mapping)) {
            lines.push(`        {${fromId}, ${toId}},`);
        }
        lines.push('    }},');
    }
    lines.push('};');
    return lines.join('\n');
}

async function main() {
    const raw = await fs.readFile(input, 'utf8');
    const data = JSON.parse(raw);
    const body = emitMap('kBlockMappings', data);
    const src = `// AUTOGENERATED FILE. DO NOT EDIT BY HAND.
// Regenerate: node tools/embed_translation_mappings.mjs

#include <cstdint>
#include <string>
#include <unordered_map>

namespace kprotocol::detail {

${body}

const std::unordered_map<std::string, std::unordered_map<std::int32_t, std::int32_t>>&
embedded_block_mappings() {
    return kBlockMappings;
}

} // namespace kprotocol::detail
`;
    await fs.writeFile(output, src);
    console.log(`Wrote ${output} (${Object.keys(data).length} version pairs).`);
}

main().catch(err => {
    console.error(err);
    process.exit(1);
});
