#!/usr/bin/env node
// Embed block default-state lookup tables from minecraft-data.
import { promises as fs } from 'node:fs';
import path from 'node:path';
import process from 'node:process';

const VERSIONS = ['1.8', '1.16.5', '1.21.1'];

async function main() {
    const mcd = (await import('minecraft-data')).default;
    const out = {};
    for (const v of VERSIONS) {
        const inst = mcd(v);
        const byName = {};
        for (const block of inst.blocksArray || []) {
            if (block?.name) {
                byName[block.name] = block.defaultState;
            }
        }
        out[v] = byName;
        console.log(`  ${v}: ${Object.keys(byName).length} blocks`);
    }

    const lines = [
        '// AUTOGENERATED FILE. DO NOT EDIT BY HAND.',
        '// Regenerate: node tools/embed_block_registry.mjs',
        '#include <cstdint>',
        '#include <string>',
        '#include <unordered_map>',
        '',
        'namespace kprotocol::detail {',
        '',
        'static const std::unordered_map<std::string, std::unordered_map<std::string, std::int32_t>> kBlockDefaultStates = {',
    ];
    for (const [version, mapping] of Object.entries(out)) {
        lines.push(`    {${JSON.stringify(version)}, {`);
        for (const [name, id] of Object.entries(mapping)) {
            lines.push(`        {${JSON.stringify(name)}, ${id}},`);
        }
        lines.push('    }},');
    }
    lines.push('};');
    lines.push('');
    lines.push('const std::unordered_map<std::string, std::unordered_map<std::string, std::int32_t>>&');
    lines.push('embedded_block_default_states() { return kBlockDefaultStates; }');
    lines.push('');
    lines.push('} // namespace kprotocol::detail');
    lines.push('');

    const root = path.resolve(path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1')), '..');
    await fs.writeFile(path.join(root, 'src', 'block_registry_data.cpp'), lines.join('\n'));
    console.log('Wrote src/block_registry_data.cpp');
}

main().catch(err => {
    console.error(err);
    process.exit(1);
});
