#!/usr/bin/env node
// Embeds tools/translation_mappings.json as sorted static arrays for O(log n) lookup.
import { promises as fs } from 'node:fs';
import path from 'node:path';
import process from 'node:process';

const VERSION_TABLE = [
    { display: '1.8', enumerator: 'v1_8' },
    { display: '1.12.2', enumerator: 'v1_12_2' },
    { display: '1.13', enumerator: 'v1_13' },
    { display: '1.14', enumerator: 'v1_14' },
    { display: '1.16.5', enumerator: 'v1_16_5' },
    { display: '1.17', enumerator: 'v1_17' },
    { display: '1.18', enumerator: 'v1_18' },
    { display: '1.19', enumerator: 'v1_19' },
    { display: '1.20.2', enumerator: 'v1_20_2' },
    { display: '1.20.4', enumerator: 'v1_20_4' },
    { display: '1.21.1', enumerator: 'v1_21_1' },
    { display: '1.21.4', enumerator: 'v1_21_4' },
    { display: '1.21.5', enumerator: 'v1_21_5' },
    { display: '1.21.6', enumerator: 'v1_21_6' },
    { display: '1.21.7', enumerator: 'v1_21_7' },
    { display: '1.21.9', enumerator: 'v1_21_9' },
    { display: '1.21.11', enumerator: 'v1_21_11' },
];

const DISPLAY_TO_ENUM = new Map(VERSION_TABLE.map(v => [v.display, v.enumerator]));

function parsePairKey(key) {
    const idx = key.indexOf('_to_');
    if (idx < 0) return null;
    return {
        from: key.slice(0, idx),
        to: key.slice(idx + 4),
    };
}

function emitSortedEntries(name, mapping) {
    const entries = Object.entries(mapping)
        .map(([from, to]) => ({ from: Number(from), to: Number(to) }))
        .sort((a, b) => a.from - b.from);
    const lines = [`static constexpr BlockMappingEntry ${name}[] = {`];
    for (const e of entries) {
        lines.push(`    {${e.from}, ${e.to}},`);
    }
    lines.push('};');
    return { lines: lines.join('\n'), count: entries.length, name };
}

function comparePair(a, b) {
    if (a.from_enum !== b.from_enum) return a.from_enum < b.from_enum ? -1 : 1;
    if (a.to_enum !== b.to_enum) return a.to_enum < b.to_enum ? -1 : 1;
    return 0;
}

async function main() {
    const root = path.resolve(path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1')), '..');
    const input = path.join(root, 'tools', 'translation_mappings.json');
    const output = path.join(root, 'src', 'translation_mappings_data.cpp');
    const raw = await fs.readFile(input, 'utf8');
    const data = JSON.parse(raw);

    const pairBlocks = [];
    const pairDescriptors = [];

    for (const [key, mapping] of Object.entries(data)) {
        const parsed = parsePairKey(key);
        if (!parsed) continue;
        const fromEnum = DISPLAY_TO_ENUM.get(parsed.from);
        const toEnum = DISPLAY_TO_ENUM.get(parsed.to);
        if (!fromEnum || !toEnum) {
            console.warn(`Skipping unknown pair key ${key}`);
            continue;
        }
        const tableName = `kMap_${fromEnum}_to_${toEnum}`;
        const emitted = emitSortedEntries(tableName, mapping);
        pairBlocks.push(emitted.lines);
        pairDescriptors.push({
            from_enum: fromEnum,
            to_enum: toEnum,
            table: tableName,
            count: emitted.count,
        });
    }

    pairDescriptors.sort((a, b) => comparePair(a, b));

    const descriptorLines = pairDescriptors.map(p =>
        `    {KnownVersion::${p.from_enum}, KnownVersion::${p.to_enum}, ${p.table}, ${p.count}},`
    );

    const src = `// AUTOGENERATED FILE. DO NOT EDIT BY HAND.
// Regenerate: node tools/embed_translation_mappings.mjs

#include "kprotocol/version.hpp"

#include <cstdint>
#include <optional>

namespace kprotocol::detail {

struct BlockMappingEntry {
    std::int32_t from;
    std::int32_t to;
};

struct BlockMappingTable {
    KnownVersion from;
    KnownVersion to;
    const BlockMappingEntry* entries;
    std::size_t count;
};

${pairBlocks.join('\n\n')}

static constexpr BlockMappingTable kBlockPairTables[] = {
${descriptorLines.join('\n')}
};

static constexpr std::size_t kBlockPairTableCount = sizeof(kBlockPairTables) / sizeof(kBlockPairTables[0]);

const BlockMappingTable* find_block_table(KnownVersion from, KnownVersion to) noexcept {
    std::size_t lo = 0;
    std::size_t hi = kBlockPairTableCount;
    while (lo < hi) {
        const std::size_t mid = lo + (hi - lo) / 2;
        const auto& row = kBlockPairTables[mid];
        if (row.from < from || (row.from == from && row.to < to)) {
            lo = mid + 1;
        } else if (row.from > from || (row.from == from && row.to > to)) {
            hi = mid;
        } else {
            return &row;
        }
    }
    return nullptr;
}

std::optional<std::int32_t> lookup_block_mapping(
    KnownVersion from,
    KnownVersion to,
    std::int32_t source_id) noexcept {

    const BlockMappingTable* table = find_block_table(from, to);
    if (table == nullptr || table->count == 0) {
        return std::nullopt;
    }

    std::size_t lo = 0;
    std::size_t hi = table->count;
    while (lo < hi) {
        const std::size_t mid = lo + (hi - lo) / 2;
        const auto& entry = table->entries[mid];
        if (entry.from < source_id) {
            lo = mid + 1;
        } else if (entry.from > source_id) {
            hi = mid;
        } else {
            return entry.to;
        }
    }
    return std::nullopt;
}

} // namespace kprotocol::detail
`;

    await fs.writeFile(output, src);
    let total = 0;
    for (const p of pairDescriptors) total += p.count;
    console.log(`Wrote ${output} (${pairDescriptors.length} version pairs, ${total} mapping entries).`);
}

main().catch(err => {
    console.error(err);
    process.exit(1);
});
