#!/usr/bin/env node
// Embed entity metadata key -> index maps from minecraft-data metadataKeys order.
import { promises as fs } from 'node:fs';
import path from 'node:path';
import process from 'node:process';

const VERSION = '1.21.1';

async function main() {
    const mcd = (await import('minecraft-data')).default(VERSION);
    const out = {};
    for (const entity of mcd.entitiesArray || []) {
        if (!entity?.name || !Array.isArray(entity.metadataKeys)) {
            continue;
        }
        const indices = {};
        entity.metadataKeys.forEach((key, index) => {
            indices[key] = index;
        });
        out[entity.name] = indices;
    }
    console.log(`  ${Object.keys(out).length} entities`);

    const lines = [
        '// AUTOGENERATED FILE. DO NOT EDIT BY HAND.',
        '// Regenerate: node tools/embed_metadata_registry.mjs',
        '#include <cstdint>',
        '#include <string>',
        '#include <unordered_map>',
        '',
        'namespace kprotocol::detail {',
        '',
        'static const std::unordered_map<std::string, std::unordered_map<std::string, std::uint8_t>> kEntityMetadataIndices = {',
    ];
    for (const [entity, indices] of Object.entries(out)) {
        lines.push(`    {${JSON.stringify(entity)}, {`);
        for (const [key, index] of Object.entries(indices)) {
            lines.push(`        {${JSON.stringify(key)}, static_cast<std::uint8_t>(${index})},`);
        }
        lines.push('    }},');
    }
    lines.push('};');
    lines.push('');
    lines.push('const std::unordered_map<std::string, std::unordered_map<std::string, std::uint8_t>>&');
    lines.push('embedded_entity_metadata_indices() { return kEntityMetadataIndices; }');
    lines.push('');
    lines.push('} // namespace kprotocol::detail');
    lines.push('');

    const root = path.resolve(path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1')), '..');
    await fs.writeFile(path.join(root, 'src', 'metadata_registry_data.cpp'), lines.join('\n'));
    console.log('Wrote src/metadata_registry_data.cpp');
}

main().catch(err => {
    console.error(err);
    process.exit(1);
});
